#!/usr/bin/python3
import time
import os
import sys
import subprocess
import signal
import time
from urllib.parse import urlparse

def print_err(err):
    sys.stderr("ERROR: ", err)
    sys.exit(1)

if len(sys.argv) < 3:
    print_err("enter cookie file and URL")

cookie_file = sys.argv[1]
url = sys.argv[2]
parsed = urlparse(url)
port = parsed.port
address = parsed.netloc
tunnel_entrance = "127.0.0.1:33333"

stunnel_config = f"\
pid = \n\
[service]\n\
client = yes\n\
accept = {tunnel_entrance}\n\
connect = {address}:443\n"

if url[:5] == "http:":
    os.system("./testhttp_raw " + address + ":" + port + " " + cookie_file + " " + url)
elif url[:6] == "https:":
    os.system(f"echo '{stunnel_config}' | stunnel -fd 0 &> /dev/null")
    time.sleep(1)
    os.system("./testhttp_raw " + tunnel_entrance + " " + cookie_file + " " + url)
    os.system(f"kill -9 $(pidof stunnel) &> /dev/null")
else:
    print_err("enter correct URL")
